name: SQLite Tests

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: [ '8.2', '8.1', '8.0', '7.4', '7.3', '7.2' ]
        dependency-stability: [ prefer-stable ]
        laravel: [ '10.*', '9.*', '8.*', '7.*', '6.*' ]

        include:
          - laravel: 10.*
            testbench: 8.*
            dbal: ^3.1.2
          - laravel:  9.*
            testbench: 7.*
            dbal: ^3.1.2
          - laravel:  8.*
            testbench: 6.*
            dbal: ^3.1.2|^2.13.3
          - laravel:  7.*
            testbench: 5.*
            dbal: ^2.6
          - laravel:  6.*
            testbench: 4.*
            dbal: ^2.6
        exclude:
          - laravel: 10.*
            php-versions: 8.0
          - laravel: 10.*
            php-versions: 7.4
          - laravel: 10.*
            php-versions: 7.3
          - laravel: 10.*
            php-versions: 7.2
          - laravel: 9.*
            php-versions: 7.2
          - laravel: 9.*
            php-versions: 7.3
          - laravel: 9.*
            php-versions: 7.4
          - laravel: 8.*
            php-versions: 7.2
          - laravel: 7.*
            php-versions: 8.2
          - laravel: 7.*
            php-versions: 8.1
          - laravel: 7.*
            php-versions: 8.0
          - laravel: 6.*
            php-versions: 8.2
          - laravel: 6.*
            php-versions: 8.1

    name: P${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.dependency-stability }} - ${{ matrix.operating-system}}

    steps:
      - uses: actions/checkout@v3
      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Get Composer Cache Directory 2
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: actions-cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Laravel Dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "doctrine/dbal:${{ matrix.dbal }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-stability }} --prefer-dist --no-interaction --no-suggest

      # Code quality
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        # Set environment
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

        run: vendor/bin/phpunit --testdox